# Generated by Django 5.1.2 on 2024-10-24 21:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerprofile',
            name='role',
            field=models.CharField(default='customer', max_length=20),
        ),
    ]
