# Generated by Django 5.1.2 on 2024-10-24 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_booking', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(choices=[('PENDING', 'pending'), ('ACCEPT', 'accept'), ('REJECT', 'reject'), ('COMPLETED', 'completed')], default='PENDING', max_length=50)),
                ('tasker_price_suggestion', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('confirmed_price', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('customer', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customer_bookings', to='users.customerprofile')),
                ('service', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='services_booking', to='users.service')),
                ('tasker', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='tasker_bookings', to='users.taskerprofile')),
            ],
        ),
        migrations.CreateModel(
            name='Notification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('is_read', models.BooleanField(default=False)),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='users.taskerprofile')),
            ],
        ),
    ]
