# Generated by Django 5.1.2 on 2024-10-25 20:28

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskservices', '0001_initial'),
        ('users', '0002_customerprofile_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='customer',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='customer_bookings', to='users.customerprofile'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='service',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_booking', to='users.service'),
        ),
        migrations.AlterField(
            model_name='booking',
            name='tasker',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasker_bookings', to='users.taskerprofile'),
        ),
    ]
