# Generated by Django 5.1.2 on 2024-11-05 11:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('taskservices', '0004_notification_booking'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='price_accepted',
            field=models.BooleanField(default=False),
        ),
    ]
